name: PUBLISH

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [closed]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install packages
        run: npm install

      - name: Build source
        run: npm run build

      - name: Publish packages to npm registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - name: Deploy Docs
        run: npm run deploy-docs
             echo "NODE_AUTH_TOKEN:${{ secrets.NPM_TOKEN }}"
